### ISSUE TITLE
[BUG] Deal with Latex code in article titles - remove \footnote 

### ISSUE THREAD

**Issue by nielbock** [mpi-astronomy/arxiv_display#12]
**Describe the bug**
There is frequently Latex code in the titles of articles. Some are needed, as they contain code that belongs to the title. Others, typically based on observational data, contain a "\footnote". While the "venign" code should be transformed at some point into something human readable, the \footnote code should be discarded.

**Paper identifier**
This paper is an example for the \footnote.
https://arxiv.org/abs/2303.00044

**To Reproduce**
1. look for articles on arxiv.org that contain \footnote in their titles
2. look at arxiv_display output (see screenshot attached)

**Expected behavior**
Any text formatted with a \footnote code in any article title should not be parsed to appear in the summary produced by arxiv_display.

**Screenshots**
attached

**Your platform (please complete the following information):**
 - Device: Lenovo Notebook
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
![image](https://user-images.githubusercontent.com/125987650/222679564-ead69749-0b98-4026-81ec-0a0c492d3601.png)

**Comment by mfouesneau** [comment]
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1703988/223844052-d703ebed-a202-48bc-8c88-25dc879ab552.png">

fixed in `arxiv_on_deck_2`
