### ISSUE TITLE
[FEATURE] Add a QR code to github pages webpage

### ISSUE THREAD

**Issue by ivastar** [mpi-astronomy/arxiv_display#16]
_Please have a look at the discussions, your feature may already be in the pipes_

**Is your feature request related to a problem? Please describe.**
Users want to read content without standing in front of screen.

**Describe the solution you'd like**
A QR code which opens the github webpage somewhere on the display. 

**Describe alternatives you've considered**
Printing out a QR code on a piece of paper and sticking it next to the displays? Not a bad option if you don't have time for the higher tech solutions. I'm handy with scissors and tape. 

**Additional context**
None.

**Comment by mfouesneau** [comment]
Implemented in [ea770b7](https://github.com/mpi-astronomy/arxiv_display/commit/ea770b7477b7c31fa90236dc2a077ddc3199d182)

![image](https://user-images.githubusercontent.com/1703988/227564463-40d548fa-f206-4114-976a-aaed39268876.png)
