### ISSUE TITLE
[BUG] Titles of ArXiV-Papers get truncated

### ISSUE THREAD

**Issue by nielbock** [mpi-astronomy/arxiv_display#6]
**Describe the bug**
Titles of ArXiV-Papers get truncated. It seems that symbols, punctuation marks, and/or Latex math code confuses the algorithm and truncates the title before formatting for the output. Only part of the full title is visible.

Example (see paper id below):
Example 1)
The paper title is:
CRIRES+ detection of CO emissions lines and temperature inversions on the dayside of WASP-18b and WASP-76b

Title shown on arxiv_display:
detection of CO emissions lines and temperature inversions on the dayside of WASP-18b and WASP-76b

Example 2)
Paper title: 
The Hubble PanCET program: The near-ultraviolet transmission spectrum of WASP-79b

Title in output is empty

Example 3)
Paper title:
The CARMENES search for exoplanets around M dwarfs. Line-by-line sensitivity to activity in M dwarfs

Title shown:
The CARMENES search for exoplanets around M dwarfs

**Paper identifiers**
Example 1)
https://arxiv.org/abs/2302.08736

Example 2)
https://arxiv.org/abs/2302.08736

Example 3)
https://arxiv.org/abs/2302.07916

**To Reproduce**
1. See paper on ArXiV
2. Compare to screenshot

**Expected behavior**
The code should list the full title as given by arxiv.org

**Screenshots**

**Your platform (please complete the following information):**
 - Device: Lenovo notebook
 - OS: Windows 10
 - Browser: Firefox
 - Version 109.0.1 (64-bit)

**Additional context**
none
![Screenshot 2023-02-21 at 15-06-21 MPIA Arxiv on deck!](https://user-images.githubusercontent.com/125987650/220369585-1c2c23c7-a98d-43bd-9879-36fca4b3818a.png)
![Screenshot 2023-02-21 at 15-16-35 MPIA Arxiv on deck!](https://user-images.githubusercontent.com/125987650/220369678-5150f2d3-85e3-40f4-b148-2a1b4c11af4d.png)
![Screenshot 2023-02-21 at 15-49-35 MPIA Arxiv on deck!](https://user-images.githubusercontent.com/125987650/220377774-7ef4374d-4102-4dca-af5d-1f82f01884d3.png)

**Comment by mfouesneau** [comment]
Some more information

Example 1)
https://arxiv.org/abs/2302.08736
`\title{CRIRES$^+$ detection of CO emissions lines and temperature inversions on the dayside of WASP-18b and ...}`
- this paper would not be selected anymore as a paper candidate after correcting for #8. No MPIA author (code would not even check the affiliations).
- BUG: The title is correctly found but it seems that the macro did not make it.

Example 3)
https://arxiv.org/abs/2302.07916
`\subtitle{Line-by-line sensitivity to activity in M dwarfs\thanks{Tables containing information about the sensitivity of the different lines  to activity are available in electronic form at the CDS via anonymous ftp to cdsarc.u-strasbg.fr (130.79.128.5) or via \url{ https://cdsarc.cds.unistra.fr/cgi-bin/qcat?J/A+A/}}}`
- this paper uses non-trival symbols in their directories and file names. This generates errors in my latex.
- BUG: subtitle parsing error. This paper uses subtitle macro, which did not parse correctly

Both bugs have the same parsing origin. They are corrected in arxiv_on_deck_2

https://github.com/mfouesneau/arxiv_on_deck_2/issues/6

**Comment by mfouesneau** [comment]
This issue comes from options to the \title macro
```
\title[Brightest cluster galaxies in IllustrisTNG]{The growth of brightest cluster galaxies in the TNG300 simulation: dissecting the contributions from mergers and \textit{in situ} star formation} 
```

**Comment by mfouesneau** [comment]
Corrected in arxiv_on_deck_2 (+ title/abstract rendering bugs)

[46db8b9](https://github.com/mfouesneau/arxiv_on_deck_2/commit/46db8b9894d843e4172c840e7d650aeaf757df1a)
