### ISSUE TITLE
[BUG] Algorithm highlights authors of MPIA papers that are not from MPIA

### ISSUE THREAD

**Issue by nielbock** [mpi-astronomy/arxiv_display#8]
**Describe the bug**
The algorithm highlights authors (yellow colour) that are not from MPIA. However, there is at least one author that is affiliated with MPIA. The others are not.

In this case, only Annalisa Pillepich is from MPIA. According to the preprint,  S. L. Finkelstein, H. Domínguez Sánchez, and H. C. Ferguson are not.

**Paper identifier**
https://arxiv.org/abs/2302.07277

**To Reproduce**
1. Access arxiv.org: https://arxiv.org/abs/2302.07277
2. Compare to list of MPIA employees, e.g.: https://www.mpia.de/institut/mitarbeiter?letter=F&previous_letter=

**Expected behavior**
Only A. Pillepich should have been highlighted.

**Screenshots**
Screenshot available

**Your platform (please complete the following information):**
- Device: Lenovo notebook
- OS: Windows 10
- Browser Firefox
- Version 109.0.1 (64-bit)

**Additional context**

![Screenshot 2023-02-21 at 15-27-52 MPIA Arxiv on deck!](https://user-images.githubusercontent.com/125987650/220372939-4d6674fe-96d3-46b7-bb7b-f180f45376fe.png)

**Comment by nielbock** [comment]
However, besides "Pillepich" none of the names highlighted are in the MPIA staff list.

**Comment by mfouesneau** [comment]
This bug is actually from [arxiv_on_deck](https://github.com/mfouesneau/arxiv_on_deck_2/issues/2)

Author matching updated to match total words. This does not use initials yet. 

Tested on the paper above.
